### PR TITLE
Add Retry after GameOver

### PR DESCRIPTION
**Pull request by ElGreenoProgramador**
I've created a separate class for handling all variables without globals, in order to reset status when in GAME OVER status.
While loop has been slightly changed, in order to always handle events, even if the game is over. For now SPACE key is used to restart the game after GAME OVER.

### CODE REVIEW

**Comment by ElGreenoProgramador** [comment]
@shash-2468 Is further work needed for this PR? Thanks!

**Comment by shash-suroju** [comment]
Great work @LordRibblesdale. 
Try keeping all the code in the same file.

**Comment by shash-suroju** [comment]
And what change did you do in the while loop? @LordRibblesdale

**Comment by ElGreenoProgramador** [comment]
The while loop is not bound to run boolean.
Because I needed to keep the event handling active even after the game over (which whould have caused the loop to stop), I made the loop eternal (while True, instead of while run:) and moved event handling at the beginning of the loop, and then I wrote a condition (if run) that allows the game to proceed.
If it is game over, run will be set to false, and only when another in put is pressed (in this case Spacebar), run is set to true and all needed variables are reset.

This is a similar situation with GLFW, which has an "infinite" loop (stopped only if window is closed or other inputs), and events are handled at the beginning or the end of the loop with glfwPollEvents()

**Comment by ElGreenoProgramador** [comment]
In addition, to avoid global calls, which imho would cause to write a high number of "global var" at the beginning of each required function (depending on the number of variables), I've saved all data inside a class, and now all variables are called with self.---

**Pull request merged**
